import type { Metadata } from 'next';
import { FileText, UserCheck, AlertTriangle, Brain, Copyright, Ban, Shield, Mail } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service',
};

const sections = [
  {
    icon: FileText,
    title: 'Acceptance of Terms',
    content:
      'By accessing or using PromptPilot AI, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use the service. These terms apply to all visitors, users, and others who access or use the platform.',
  },
  {
    icon: UserCheck,
    title: 'User Responsibilities',
    content:
      'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate and complete. You must notify us immediately of any unauthorized use of your account.',
  },
  {
    icon: AlertTriangle,
    title: 'Usage Rules',
    content:
      'You agree to use PromptPilot AI in compliance with all applicable local, state, national, and international laws and regulations. You may not use the service for any unlawful purpose or to violate any laws. You must not interfere with or disrupt the integrity or performance of the platform or attempt to gain unauthorized access to its systems.',
  },
  {
    icon: Brain,
    title: 'AI Limitations and Disclaimers',
    content:
      'PromptPilot AI provides AI-powered prompt analysis and optimization suggestions. These suggestions are generated by artificial intelligence models and are provided for informational and assistive purposes only. We do not guarantee the accuracy, reliability, or completeness of any analysis or suggestion. You are solely responsible for reviewing and validating any output before using it. The service is provided "as is" without warranties of any kind.',
  },
  {
    icon: Copyright,
    title: 'Intellectual Property',
    content:
      'You retain all rights to the prompts and content you submit to PromptPilot AI. By submitting content, you grant us a non-exclusive, royalty-free license to process, analyze, and store your content solely for the purpose of providing our services. The PromptPilot AI platform, including its software, design, text, graphics, and logo, is owned by PromptPilot AI and is protected by intellectual property laws.',
  },
  {
    icon: Ban,
    title: 'Prohibited Uses',
    content:
      'You may not use PromptPilot AI to generate, store, or distribute content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or invasive of another\'s privacy. You may not use the service to impersonate any person or entity. Automated scraping, data mining, or reverse engineering of the platform is strictly prohibited. Violation of these prohibitions may result in immediate termination of your account.',
  },
  {
    icon: Shield,
    title: 'Limitation of Liability',
    content:
      'In no event shall PromptPilot AI, its directors, employees, or agents be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation loss of profits, data, use, or goodwill, arising out of or in connection with your use of the service. Our total liability for any claims under these terms shall not exceed the amount you have paid us in the twelve months preceding the claim.',
  },
  {
    icon: Mail,
    title: 'Contact Information',
    content:
      'For questions about these Terms of Service, please contact us at legal@promptpilot.ai. You may also reach us by mail at PromptPilot AI, 123 Innovation Drive, San Francisco, CA 94105, United States. We will respond to all inquiries within 5 business days.',
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary-100">
            <FileText className="h-8 w-8 text-primary-600" />
          </div>
          <h1 className="text-3xl font-bold text-slate-900 sm:text-4xl">Terms of Service</h1>
          <p className="mt-3 text-sm text-slate-500">Last updated: July 1, 2026</p>
        </div>

        <div className="space-y-8">
          {sections.map((section) => (
            <div
              key={section.title}
              className="rounded-xl border border-slate-200 bg-white p-6 transition-shadow hover:shadow-sm sm:p-8"
            >
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-50">
                  <section.icon className="h-5 w-5 text-primary-600" />
                </div>
                <h2 className="text-lg font-semibold text-slate-900">{section.title}</h2>
              </div>
              <p className="text-sm leading-relaxed text-slate-600">{section.content}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
